{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-test-api",
    "version": "8.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "builder-test-api-8.4.1.jar",
          "url": "builder-test-api-8.4.1.jar",
          "size": 15329,
          "sha512": "fa526b7a5be85758d6c64dc23d0e1fd2c7502d72af2cf024385d578c67a53d320f37e96a1717c1060d79547705a941efbea1383224dc17ad887ed6a5993bd8de",
          "sha256": "0695ffddad94a68d505ecf49ad6a26470a4227dea6129fc19e4ea5bdd9a769b9",
          "sha1": "1a3d1be6c9a4bbdf73169e56e0a8b37aae6284f4",
          "md5": "aaea801723fa466ebb80d49f9441b145"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "builder-test-api-8.4.1.jar",
          "url": "builder-test-api-8.4.1.jar",
          "size": 15329,
          "sha512": "fa526b7a5be85758d6c64dc23d0e1fd2c7502d72af2cf024385d578c67a53d320f37e96a1717c1060d79547705a941efbea1383224dc17ad887ed6a5993bd8de",
          "sha256": "0695ffddad94a68d505ecf49ad6a26470a4227dea6129fc19e4ea5bdd9a769b9",
          "sha1": "1a3d1be6c9a4bbdf73169e56e0a8b37aae6284f4",
          "md5": "aaea801723fa466ebb80d49f9441b145"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.4.1-javadoc.jar",
          "url": "builder-test-api-8.4.1-javadoc.jar",
          "size": 117213,
          "sha512": "e81a2a8ccffd27b852b9057598a6f53198c9b0f59553fb68c1d55d9cb5a1a6a5e9db86b16f2e289827f15cf15646deff2997f295869f6eb537e088d948698c9d",
          "sha256": "48b70a374bb2c9b74946ef0e46099c15face727a2cd45576ef1b3771c22e4aa9",
          "sha1": "c5bf4f26322dccecd6f4ada3e69507bbf986ef44",
          "md5": "0170d5a21406cd9cef2c9715e9e0b73a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.4.1-sources.jar",
          "url": "builder-test-api-8.4.1-sources.jar",
          "size": 13848,
          "sha512": "18dce201a47e41532d86504b176a91bc7b9e73348973d9e2cd352e1445568feaa259fa2a715b2b839a1428b756aca547d6efff4471c3e2ef9d228d331705fc3a",
          "sha256": "3c282315217c726335a537c3b72c84a9e08513262a2a5b814de9a1c6ebd1ce89",
          "sha1": "48c559ec1f3c0b03e365d7c19aff85c585b45161",
          "md5": "899d627338e670c6183c81c6b89a98f4"
        }
      ]
    }
  ]
}
