{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.4.1.jar",
          "url": "gradle-settings-api-8.4.1.jar",
          "size": 9856,
          "sha512": "1f74793ea8a38f29ea68215fe2628bc5647677120885b2abc38bac431b98b5a07a1bd47dbbca54f7a7ef783aeb1169c36a72f67e79545a0606b825569afa0c6e",
          "sha256": "48fca54253cb93182afcb1173c1dbd9953aad7bf29b225b2e37ef9e1ddc01606",
          "sha1": "a50bd3ab6c6e01510dce09a3247f478be6106da2",
          "md5": "07856c8ca572bc3cdaff3799d33ba8d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.4.1.jar",
          "url": "gradle-settings-api-8.4.1.jar",
          "size": 9856,
          "sha512": "1f74793ea8a38f29ea68215fe2628bc5647677120885b2abc38bac431b98b5a07a1bd47dbbca54f7a7ef783aeb1169c36a72f67e79545a0606b825569afa0c6e",
          "sha256": "48fca54253cb93182afcb1173c1dbd9953aad7bf29b225b2e37ef9e1ddc01606",
          "sha1": "a50bd3ab6c6e01510dce09a3247f478be6106da2",
          "md5": "07856c8ca572bc3cdaff3799d33ba8d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.4.1-javadoc.jar",
          "url": "gradle-settings-api-8.4.1-javadoc.jar",
          "size": 261,
          "sha512": "8ed01c1d9885ae72bb6e8658d64429f546fda2c08b9095440c19065bbbce8f69bc3cbdb156c57e8fe62d53dd1382b92611d83459db0b91e0d76e0b078c95ddce",
          "sha256": "dde1435cd9becb240c45a96ba36fdcf852f857684dd5d52c505cda155085213b",
          "sha1": "8ff0b227db7ee1f5ecce7c64ddb2c4a07e2e4b5f",
          "md5": "c41a5ef11a5a53572032ae2710c7267c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.4.1-sources.jar",
          "url": "gradle-settings-api-8.4.1-sources.jar",
          "size": 9407,
          "sha512": "6df79e0f837aa759271722d63a2a59c223a0dd225e1841264ede83006b7a604960ef0bc0da5601754be0e9f49e527c4fd0f941ce2ecbefdf24041a39df8dd38f",
          "sha256": "5f57fa992a31a88ec7f6835b8ad7730860dfee4f74e013dec873d0fc82095acc",
          "sha1": "01a728bf487c74ef5581e379c2e192002c887753",
          "md5": "92e0e5bc845cffbda4b682e8abd1e908"
        }
      ]
    }
  ]
}
